name: Flutter Build APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Run Build
      run: |
        flutter create --org com.najma.app najma_project
        cd najma_project
        flutter pub get
        flutter build apk --release
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: najma-app-release
        path: najma_project/build/app/outputs/flutter-apk/app-release.apk
